name: Trigger Action on a CRON Schedule

on:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: '*/10 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://selflearning-vercel-deploy-test.vercel.app/addNumber' \
          --header 'Authorization: Bearer ${{  }}'


